### ISSUE TITLE
gpl + classpath exception

### ISSUE THREAD

**Issue by maxandersen** [thomasokken/jdbcnav#2]
I see the license is GPL - thats a bit problematic for Java code as hard to then combine with others - have you considered using GPL + classpath exception which is what the OpenJDK uses?

**Comment by thomasokken** [comment]
JDBC Navigator is a stand-alone app, not a library. GPLv2 seems appropriate to me.

**Comment by maxandersen** [comment]
fair enough - i'm just not a fan of not classpath exception :)
